<?php

return [
    'houses' => [
        [
            'title' => 'La Casa di Luce',
            'address' => 'Via del Mare, 00126 Roma',
            'latitude' => '41.79246',
            'longitude' => '12.38622',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 100,
            'description' => 'Un\' accogliente dimora con ampie finestre che permettono alla luce naturale di riempire gli spazi, offrendo un ambiente luminoso e rilassante.',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Vista Mare Sereno',
            'address' => 'Piazza del Popolo, 00187 Roma',
            'latitude' => '41.91048',
            'longitude' => '12.47623',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Una casa affacciata sul mare con una vista mozzafiato che offre una quiete e serenità uniche, ideale per godersi tramonti indimenticabili.',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Rifugio Montano',
            'address' => 'Via Napoleone, 20121 Milano',
            'latitude' => '45.46818',
            'longitude' => '9.19532',
            'beds' => 3,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Un accogliente rifugio situato tra le montagne, perfetto per gli amanti della natura e delle escursioni',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Dolce Tranquillità',
            'address' => 'Via Stazione, 32043 Cortina d\'Ampezzo',
            'latitude' => '46.53914',
            'longitude' => '12.13643',
            'beds' => 6,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 150,
            'description' => 'Una casa che promette una pausa rilassante dalla frenesia quotidiana, offrendo un ambiente tranquillo e sereno',
            'cover_image'=> 'https://placehold.co/600x400',
         ],
        [
            'title' => 'Casa Soleggiata',
            'address' => 'Via Monte Napoleone, 20121 Milano',
            'latitude' => '45.46818',
            'longitude' => '9.19532',
            'beds' => 3,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Una residenza accogliente e luminosa, baciata dal sole tutto il giorno, perfetta per godersi la calda atmosfera diurna',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Paradiso Sospeso',
            'address' => 'Via Faloria, 32043 Cortina d\'Ampezzo',
            'latitude' => '46.53269',
            'longitude' => '12.14363',
            'beds' => 6,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 150,
            'description' => 'Una casa incantevole, apparentemente sospesa nel tempo e nello spazio, ideale per una fuga romantica',
            'cover_image'=> 'https://placehold.co/600x400',
         ],
        [
            'title' => 'Angolo di Pace',
            'address' => 'Piazza Navona, 00186 Roma',
            'latitude' => '41.89913',
            'longitude' => '12.4732',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 80,
            'description' => 'Un luogo dove ritrovare l\'armonia interiore e godersi un ambiente calmo e pacifico, lontano dal caos della vita quotidiana',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Rifugio delle Colline',
            'address' => 'Via del Castello, 53037 San Gimignano SI, Italia',
            'latitude' => '43.46754',
            'longitude' => '11.04466',
            'beds' => 10,
            'rooms' => 5,
            'bathrooms' => 5,
            'sq_meters' => 400,
            'description' => 'Una dimora affascinante immersa nelle colline, offrendo un rifugio ideale per rigenerarsi e godere della natura circostante',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Nido Accogliente',
            'address' => 'Campo San Polo, 30125 Venezia, Italia',
            'latitude' => '45.43735',
            'longitude' => '12.3296',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 80,
            'description' => 'Una casa intima e accogliente, perfetta per una fuga romantica o un soggiorno tranquillo e confortevole',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Cielo Blu Residenza',
            'address' => 'Via San Giovanni, 50028 Tavarnelle Val di Pesa FI, Italia',
            'latitude' => '43.56389',
            'longitude' => '11.17425',
            'beds' => 8,
            'rooms' => 4,
            'sq_meters' => 200,
            'bathrooms' => 4,
            'description' => 'Una residenza che offre un\'esperienza unica sotto un cielo sempre blu, ideale per un soggiorno di relax e serenità',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Vento Marinaio',
            'address' => 'Via Mazzini, 19018 Vernazza SP, Italia',
            'latitude' => '44.13448',
            'longitude' => '9.68334',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Una residenza caratterizzata da una brezza marina rinfrescante e un\'atmosfera che richiama il mare, perfetta per chi ama il contatto con l\'oceano',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Cottage Incantato',
            'address' => 'Via Del Porto, 06069 Tuoro sul Trasimeno PG, Italia',
            'latitude' => '43.20603',
            'longitude' => '12.07734',
            'beds' => 6,
            'rooms' => 3,
            'bathrooms' => 3,
            'sq_meters' => 150,
            'description' => 'Un\'affascinante dimora dal fascino fiabesco, immersa in un giardino incantato, perfetta per vivere una favola moderna',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Casale Fiorito',
            'address' => 'Piazza della Signoria, 50122 Firenze FI, Italia',
            'latitude' => '43.76954',
            'longitude' => '11.25598',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 50,
            'description' => 'Un antico casale circondato da giardini fioriti e profumati, offrendo un\'oasi di tranquillità e bellezza',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Rifugio Selvaggio',
            'address' => 'Via Regina, 22010 Cernobio, Italia',
            'latitude' => '45.8523',
            'longitude' => '9.08894',
            'beds' => 8,
            'rooms' => 4,
            'bathrooms' => 3,
            'sq_meters' => 200,
            'description' => 'Una residenza avvolta dalla natura selvaggia e incontaminata, ideale per gli amanti dell\'avventura e della privacy',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Alba Magica',
            'address' => 'Corso Italia, 80067 Sorrento NA, Italia',
            'latitude' => '40.62676',
            'longitude' => '14.38085',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 100,
            'description' => 'Una casa dove ogni alba regala uno spettacolo mozzafiato, immergendo gli ospiti in una magia mattutina senza pari',
            'cover_image'=> 'https://placehold.co/600x400',
         ],
        [
            'title' => 'Oasi Verde',
            'address' => 'Via del Mandarino, 91010 San Vito Lo Capo TP, Italia',
            'latitude' => '38.13129',
            'longitude' => '12.73482',
            'beds' => 6,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Un\'incantevole oasi di verde e tranquillità, ideale per chi cerca una fuga dalla vita cittadina',
            'cover_image'=> 'https://placehold.co/600x400',
            
        ],
        [
            'title' => 'Casa dei Sogni',
            'address' => 'Via dei Melograni, 50142 Firenze',
            'latitude' => '43.77741',
            'longitude' => '11.22011',
            'beds' => 6,
            'rooms' => 3,
            'bathrooms' => 2,
            'sq_meters' => 120,
            'description' => 'Una dimora che sembra uscita direttamente dai sogni, offrendo un ambiente confortevole e accogliente per creare ricordi indimenticabili',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Dimora Relax',
            'address' => 'Viale della Vittoria, 00122 Roma',
            'latitude' => '41.72929,',
            'longitude' => '12.28798',
            'beds' => 2,
            'rooms' => 1,
            'bathrooms' => 1,
            'sq_meters' => 80,
            'description' => 'Una casa progettata per offrire il massimo relax, con spazi confortevoli e un\'atmosfera accogliente',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Mare e Monti Hideaway',
            'address' => 'Viale dei Pini, 50142 Firenze',
            'latitude' => '43.77924',
            'longitude' => '11.21495',
            'beds' => 3,
            'rooms' => 2,
            'bathrooms' => 1,
            'sq_meters' => 90,
            'description' => 'Un rifugio nascosto tra il mare e le montagne, offrendo una varietà di esperienze naturali e paesaggi mozzafiato',
            'cover_image'=> 'https://placehold.co/600x400',
        ],
        [
            'title' => 'Palazzo della Quietudine',
            'address' => 'Viale Trento, 47921 Rimini',
            'latitude' => '44.06591',
            'longitude' => '12.5792',
            'beds' => 4,
            'rooms' => 2,
            'bathrooms' => 2,
            'sq_meters' => 70,
            'description' => 'Una dimora maestosa che promette tranquillità assoluta e un\'esperienza di soggiorno regale',
            'cover_image'=> 'https://placehold.co/600x400',
         ],
        
    ],



    'extras' => [
        [
            'name'=> 'cucina', 
            'color'=> '#7A3F98',
            'icon'=> '<i class="fa-solid fa-kitchen-set"></i>',
            'icon_vue'=> 'fa-solid fa-kitchen-set',
        ],
        [
            'name'=> 'wi-fi', 
            'color'=> '#2ECC71',
            'icon'=> '<i class="fa-solid fa-wifi"></i>',
            'icon_vue'=> 'fa-solid fa-wifi',
           
        ],
        [
            'name'=> 'giardino', 
            'color'=> '#F39C12',
            'icon'=> '<i class="fa-solid fa-seedling"></i>',
            'icon_vue'=> 'fa-solid fa-seedling',
        ],
        [
            'name'=> 'posto auto', 
            'color'=> '#3498DB',
            'icon'=> '<i class="fa-solid fa-square-parking"></i>',
            'icon_vue'=> 'fa-solid fa-square-parking',
        ],
        [
            'name'=> 'tv', 
            'color'=> '#E74C3C',
            'icon'=> '<i class="fa-solid fa-tv"></i>',
            'icon_vue'=> 'fa-solid fa-tv',
        ],
        [
            'name'=> 'piscina', 
            'color'=> '#1ABC9C',
            'icon'=> '<i class="fa-solid fa-person-swimming"></i>',
            'icon_vue'=> 'fa-solid fa-person-swimming',
        ],
        [
            'name'=> 'aria condizionata', 
            'color'=> '#D35400',
            'icon'=> '<i class="fa-solid fa-wind"></i>',
            'icon_vue'=> 'fa-solid fa-wind',
        ],
        [
            'name'=> 'vista mare', 
            'color'=> '#8E44AD',
            'icon'=> '<i class="fa-solid fa-water"></i>',
            'icon_vue'=> 'fa-solid fa-water',
        ],
    ],

    'sponsorships' => [
        [
            'price'=> 2.99,
            'duration' => 24,
            'name' => 'bronze',
             
        ],
        [
            'price'=> 5.99,
            'duration' => 48,
            'name' => 'silver',
        ],
        [
            'price'=>9.99,
            'duration' => 72,
            'name' => 'gold',
        ],
    ],

    'users' => [
        [
            'name' => 'Mario',
            'last_name' => 'Rossi',
            'email' => 'mario.rossi@example.com',
            'date_of_birth' => '1990-08-15',
            'password' => 'securepass1'
        ],
        [
            'name' => 'Anna',
            'last_name' => 'Bianchi',
            'email' => 'anna.bianchi@example.com',
            'date_of_birth' => '1985-03-22',
            'password' => 'strongpass2'
        ],
        [
            'name' => 'Luca',
            'last_name' => 'Verdi',
            'email' => 'luca.verdi@example.com',
            'date_of_birth' => '1995-11-10',
            'password' => 'safepass3'
        ],
        [
            'name' => 'Giulia',
            'last_name' => 'Neri',
            'email' => 'giulia.neri@example.com',
            'date_of_birth' => '1988-06-05',
            'password' => 'secretword4'
        ],
        [
            'name' => 'Alessio',
            'last_name' => 'Giallo',
            'email' => 'alessio.giallo@example.com',
            'date_of_birth' => '1992-09-18',
            'password' => 'password123'
        ]
    ],


];